### ISSUE TITLE
Sounds interesting

### ISSUE THREAD

**Issue by timaschew** [suiteplus/gulp-nstools#1]
Is it already working?
Would be nice to have some starting point how to setup. Or can I help you somehow?

**Comment by danieljoppi** [comment]
started ... 
you can help :) .. https://github.com/suiteplus/gulp-nstools/wiki

**Comment by danieljoppi** [comment]
release v0.1.0 ... finished 

```bash
npm install gulp-nstools --save-dev
```

You can

**Comment by timaschew** [comment]
great! I will try it out soon.
